version: "2"

services:
    wordpress:
        depends_on: 
            - mariadb
        build:
            context: ./requirements/wordpress
        image: my_wordpress:1.0
        container_name: wordpress
        ports: 
            - "9000:9000"
        command: sh /start_wp.sh
        env_file:
            - .env
        restart: always
        volumes:
            - /home/hdurand/data/wordpress_vol:/var/www/html/
        networks:
            - ng_wp
            - mdb_wp

    mariadb: 
        build: ./requirements/mariadb/
        container_name: mariadb
        image: my_mariadb:1.0
        ports:
            - "3306:3306"
        command: sh /tmp/initmdb.sh
        env_file:
            - .env
        restart: always
        volumes:
            - /home/hdurand/data/mariadb_vol:/var/lib/mysql/
        networks:
            - mdb_wp

    nginx:
        depends_on:
            - wordpress
        build: 
            context: ./requirements/nginx/
            dockerfile: Dockerfile
        image: my_nginx:1.0
        container_name: incestginx
        ports:
            - "443:443"
        command: nginx -g "daemon off;"
        env_file:
            - .env
        restart: always
        volumes:
            - /home/hdurand/data/wordpress_vol:/var/www/html/
        networks:
            - ng_wp

networks:
    ng_wp:
    mdb_wp:
